# system configuration
system:
  env: "dev"
  addr: ":9678"
  db-type: "mysql"
  oss-type: "tencent-cos" # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

mysql:
  path: "127.0.0.1"
  port: "3306"
  config: "charset=utf8mb4&parseTime=true&loc=Local"
  db-name: "opbook"
  username: "root"
  password: "root"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

db-list: [
    {
      disabled: true, # 是否启用
      type: "", # 数据库的类型,目前支持mysql、pgsql
      alias-name: "", # 数据库的名称,注意: alias-name 需要在db-list中唯一
      path: "",
      port: "",
      config: "",
      db-name: "",
      username: "",
      password: "",
      max-idle-conns: 10,
      max-open-conns: 100,
      log-mode: "",
      log-zap: false,
    },
  ]

# zap logger configuration
zap:
  level: "info"
  format: "console"
  prefix: "[opbook-server]"
  director: "log"
  show-line: true
  encode-level: "CapitalColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true

# jwt configuration
jwt:
  signing-key: "qmPlus"
  expires-time: 604800
  buffer-time: 86400
  issuer: "qmPlus"

# local configuration
local:
  path: "uploads" # 资源所在项目根下的目录名
  avator: "avator" # path目录下的头像目录
  book: "book" # path目录下的书籍目录
  # 如果静态资源为本地存储，那么访问资源url为http://IP:PORT/relativePath/file, 其中file为文件的相对路径
  relativePath: "/uploads"
  addr: "http://localhost:9678"

# tencent cos configuration
tencent-cos:
  bucket: "opbook-1304588036"
  region: "ap-hongkong"
  secret-id: "AKIDFG6i5LCAj0EguvuEAuSCiAU1cxAJjetv"
  secret-key: "0pOjqhV9apvxwhBcw2e06TbUJ3atSlT4"
  base-url: "https://opbook-1304588036.cos.ap-hongkong.myqcloud.com"
  path-prefix: "file"

# redis configuration
redis:
  db: 0
  addr: "110.42.176.87:6379"
  password: "123456"

# timer task update db table
Timer:
  start: true
  spec: "@every 10m"
